### ISSUE TITLE
Pretzel Doesn't work on windows 3.1

### ISSUE THREAD

**Issue by Stasonis** [Interfiber/Pretzel#7]
Seriously? This is critical to me using the product. You need to get on this support NOW!  Like really now!

**Comment by Interfiber** [comment]
DID YOU READ THE TITLE "A package manager for MACOSX!!!!!!!!!"
Not windows!!

**Comment by Interfiber** [comment]
Plus windows 3.1!!!! That version isn't sold any MORE!!!

**Comment by Interfiber** [comment]
Thanks for helpping me test issues!

**Comment by Interfiber** [comment]
`<img src="https://www.logolynx.com/topic/windows+3.1#&gid=1&pid=4/>`

**Comment by Interfiber** [comment]
[windows is OLD!!!](https://www.logolynx.com/topic/windows+3.1#&gid=1&pid=4)
